### ISSUE TITLE
目录展示插件在移植的时候遇到的bug

### ISSUE THREAD

**Issue by YSMull** [fooleap/fooleap.github.io#1]
## bug描述
在移植您的目录插件到我自己的博客的时候，发现虽然可以实现正常的目录跳转，但是鼠标点击某一标题，active属性总是设置为上一个标题，导致显示不正常。
同样的代码，在您的博客上却是正常的，调试时发现您博客的`subTitles[i].offsetTop`总是比`pos`多了32。当去掉您博客的`.page-main`的`margin: 32px auto; `时，即可复现该bug。
## 解决办法
https://github.com/fooleap/fooleap.github.io/blob/master/assets/js/main.js 
344行的`sections[i] < pos`应该改为`sections[i] <= pos`
同时建议将
```javascript
var sectionIds = [];
var sections = [];
```
放到` function tocScroll()`内部，否则其size会无限增长。

**Comment by YSMull** [comment]
https://github.com/fooleap/fooleap.github.io/blob/master/assets/js/main.js
348行的
```
'[href="#' + sectionIds[i] + '"'
```
应该改为
```
'[href="#' + sectionIds[i] + '"]'
```
否则safari浏览器会报错。

**Comment by fooleap** [comment]
@YSMull 多谢，这个写漏了
